SUPABASE_URL = "https://lrcndjpcphveawcukbdd.supabase.co"

SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyY25kanBjcGh2ZWF3Y3VrYmRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ4MTI1NDUsImV4cCI6MjEwMDM4ODU0NX0._vSnaZVJHe6hXNmGTZXO_7UWR5xo9mWZzHRn91JXAHc"